source 'http://rubygems.org'
gem 'rake'
gem 'ffi'
gem 'excel_to_code', '0.2.19'
#gem 'excel_to_code', :git => '/home/ubuntu/excel_to_code', :branch => 'fewerSaveLoads'
#gem 'excel_to_code', :git => '/home/ubuntu/excel_to_code', :branch => 'master'
gem 'minitest'
